# Generated by Django 4.0.4 on 2022-04-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=False, max_length=50, unique=True, verbose_name='Module Name')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(default=False, max_length=50, verbose_name='Display Name')),
                ('order', models.IntegerField(blank=True, default=0, null=True, verbose_name='Order')),
                ('chained_module', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent_module_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.module')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
