# Generated by Django 4.0.4 on 2022-04-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subdomain_prefix', models.CharField(max_length=100, unique=True)),
                ('is_master', models.BooleanField(default=False)),
                ('db_name', models.CharField(max_length=100)),
                ('saml_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saml.samlconfiguration')),
            ],
        ),
    ]
